### ISSUE TITLE
option to make the main item link the HN comments instead of the submitted link

### ISSUE THREAD

**Issue by fletom** [kaini/hnbest#6]
Usually the most interesting part of HN is the discussion, not the link itself.

Personally, I browse my feeds using hotkeys (JK to navigate next/previous, V to open in a background tab) and often end up missing the discussion because the submitted link gets opened instead of the comments link.

I've never written Ruby myself but if you don't have time to add this feature then I'll do my best on a writing PR for it.

Thanks!

**Comment by kaini** [comment]
It should be very simple to do this, I'll take a look at it in some days.

**Comment by fletom** [comment]
thank you!

**Comment by kaini** [comment]
Done! You can now use the get parameter link_comments=1 to link to the discussion instead of to the submitted URL.

**Comment by fletom** [comment]
Great, thanks.

It looks a little weird now though in most RSS readers, because there's an H1 in the description as well as the actual title.

![image 2017-07-01 at 7 33 35 am public](https://user-images.githubusercontent.com/127497/27761760-a288b0fc-5e30-11e7-96e3-42550ce2f25f.png)

Perhaps the following would work better in the template?

```
          %p
            %a{:href => item[:url]} Link
          %p
            %a{:href => item[:commentsurl]} Comments
```

**Comment by kaini** [comment]
Indeed, that's looking strange. I changed it to `p`.

**Comment by fletom** [comment]
Looks better now.

There's still one more small issue. In RSS readers the `<guid>` field often takes priority over `<link>` as the permalink, which means that Feedly for example still shows the same direct link instead of the comments link even with the new parameter.

See: https://www.feedvalidator.org/docs/error/InvalidPermalink.html

Can you add the same conditional to `<guid>` as you put in `<link>`?

**Comment by kaini** [comment]
Done. Note that this might lead to some duplicate entries since all the GUIDs changed for `link_comments=1`.

**Comment by fletom** [comment]
Wonderful, it works perfectly now. Thank you so much.
